// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Use Neon's direct (unpooled) connection string here, not the pooled
    // one — the pooled connection can't create the shadow DB `migrate dev`
    // needs, and at our scale (6-15 users) pooling isn't worth the added
    // config surface. This installed Prisma version's config schema has no
    // `directUrl` field (only `url`/`shadowDatabaseUrl`), so one URL it is.
    url: process.env["DATABASE_URL"],
  },
});
